version: '3.9'
services:
    web:
      build: .
      volumes: 
        - ./src:/var/www/html/
      ports:
        - 7001:80
    db:
      image: mysql
      volumes: 
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: docker_database_ems_live
      ports:
        - 5306:3306
